export type ProviderAuthType = 'api-key' | 'cookie' | 'oauth' | 'local' | 'none';

export type ProviderCategory = 
  | 'frontier'
  | 'web-cookie'
  | 'inference-hosts'
  | 'regional'
  | 'enterprise-cloud'
  | 'media-audio'
  | 'cloud-agent'
  | 'local-free'
  | 'gateways';

export interface ProviderCatalogItem {
  id: string;
  name: string;
  category: ProviderCategory;
  categoryLabel: string;
  authTypes: ProviderAuthType[];
  badge: string;
  description: string;
  website: string;
  docUrl?: string;
  cookieHint?: string;
  cookieFields?: string[];
  placeholder?: string;
  defaultBaseUrl?: string;
  models?: string[];
  supportsTools?: boolean;
  supportsVision?: boolean;
}

export const SUTRA_ALL_PROVIDERS: ProviderCatalogItem[] = [
  // 1. FRONTIER LABS (13)
  {
    id: 'google',
    name: 'Google Gemini',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key', 'cookie', 'oauth'],
    badge: 'Gemini 3 / 3.7 Pro',
    description: 'Google DeepMind flagship models with up to 2M multimodal context.',
    website: 'https://aistudio.google.com',
    docUrl: 'https://aistudio.google.com/app/apikey',
    placeholder: 'AIzaSy...',
    cookieHint: 'Paste __Secure-1PSID and __Secure-1PSIDTS from gemini.google.com',
    cookieFields: ['__Secure-1PSID', '__Secure-1PSIDTS'],
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key', 'cookie'],
    badge: 'GPT-5 Family / o-series',
    description: 'OpenAI flagship reasoning, coding, and multimodal intelligence.',
    website: 'https://platform.openai.com',
    docUrl: 'https://platform.openai.com/api-keys',
    placeholder: 'sk-proj-...',
    cookieHint: 'Paste __Secure-next-auth.session-token from chatgpt.com',
    cookieFields: ['__Secure-next-auth.session-token'],
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key', 'cookie'],
    badge: 'Claude 5 Family',
    description: 'Claude 5 flagship hybrid reasoning with Sonnet agentic tool execution.',
    website: 'https://anthropic.com',
    docUrl: 'https://console.anthropic.com/settings/keys',
    placeholder: 'sk-ant-...',
    cookieHint: 'Paste sessionKey cookie from claude.ai',
    cookieFields: ['sessionKey'],
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key', 'cookie'],
    badge: 'DeepSeek R1 & V3',
    description: 'DeepSeek-R1 open chain-of-thought mathematical reasoning and DeepSeek-V3.',
    website: 'https://deepseek.com',
    docUrl: 'https://platform.deepseek.com/api_keys',
    placeholder: 'sk-...',
    cookieHint: 'Paste userToken cookie value from chat.deepseek.com',
    cookieFields: ['userToken'],
    supportsTools: true,
    supportsVision: false,
  },
  {
    id: 'groq',
    name: 'Groq Cloud LPUs',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key'],
    badge: '500+ tok/s Ultra Speed',
    description: 'Ultra-low latency LPU hardware running GPT-OSS, Qwen, and Llama 3.3.',
    website: 'https://groq.com',
    docUrl: 'https://console.groq.com/keys',
    placeholder: 'gsk_...',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'xai',
    name: 'xAI Grok',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key', 'cookie'],
    badge: 'Grok 4 / Grok Code Fast',
    description: 'xAI Grok frontier models with deep real-time web awareness.',
    website: 'https://x.ai',
    docUrl: 'https://console.x.ai',
    placeholder: 'xai-...',
    cookieHint: 'Paste full sso and sso-rw cookies from grok.com',
    cookieFields: ['sso', 'sso-rw'],
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key', 'cookie'],
    badge: 'Mistral Large / Codestral',
    description: 'Mistral Large 2411, Codestral 2501, and Pixtral 12B multimodal.',
    website: 'https://mistral.ai',
    docUrl: 'https://console.mistral.ai/api-keys',
    placeholder: 'mis_...',
    cookieHint: 'Paste session cookie from chat.mistral.ai',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'meta-llama',
    name: 'Meta AI / Llama',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key', 'cookie'],
    badge: 'Llama 4 Family',
    description: 'Meta Llama 4 Maverick and Scout plus Llama Guard safety models.',
    website: 'https://llama.meta.com',
    placeholder: 'sk-...',
    cookieHint: 'Paste ecto_1_sess cookie from meta.ai',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key'],
    badge: 'Command A / Embed',
    description: 'Command A enterprise multilingual reasoning and Embed v3.',
    website: 'https://cohere.com',
    docUrl: 'https://dashboard.cohere.com/api-keys',
    placeholder: 'coh_...',
    supportsTools: true,
  },
  {
    id: 'ai21',
    name: 'AI21 Labs',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key'],
    badge: 'Jamba 1.6 Mini/Large',
    description: 'Hybrid SSM-Transformer architecture for ultra-long 256K context.',
    website: 'https://ai21.com',
    docUrl: 'https://studio.ai21.com/account/api-key',
    placeholder: 'ai21_...',
    supportsTools: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key', 'cookie'],
    badge: 'Sonar Reasoning Pro',
    description: 'Live web-grounded search reasoning with real-time citations.',
    website: 'https://perplexity.ai',
    docUrl: 'https://perplexity.ai/settings/api',
    placeholder: 'pplx-...',
    cookieHint: 'Paste __Secure-next-auth.session-token from perplexity.ai',
    cookieFields: ['__Secure-next-auth.session-token'],
    supportsTools: true,
  },
  {
    id: 'github',
    name: 'GitHub Models',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key', 'oauth'],
    badge: 'Azure AI Marketplace',
    description: 'GPT-5, Claude 5, and Llama 4 free tier via GitHub Token.',
    website: 'https://github.com/marketplace/models',
    docUrl: 'https://github.com/settings/tokens',
    placeholder: 'ghp_...',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'reka',
    name: 'Reka AI',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key'],
    badge: 'Reka Core / Flash / Spark',
    description: 'Multimodal reasoning models built by former DeepMind and Google Brain researchers.',
    website: 'https://reka.ai',
    docUrl: 'https://docs.reka.ai',
    placeholder: 'rk_...',
    defaultBaseUrl: 'https://api.reka.ai/v1',
  },

  // 2. WEB COOKIE AUTH (FREE & SUBSCRIPTION) (25)
  {
    id: 'chatgpt-web',
    name: 'ChatGPT Web (Plus/Pro)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Free/Plus)',
    description: 'Use your existing ChatGPT Plus/Pro web subscription with zero API costs.',
    website: 'https://chatgpt.com',
    cookieHint: 'DevTools → Application → Cookies → __Secure-next-auth.session-token',
    cookieFields: ['__Secure-next-auth.session-token', 'cf_clearance'],
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'claude-web',
    name: 'Claude Web (Pro)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Pro)',
    description: 'Use your Claude Pro web subscription (Claude 5 & Artifacts).',
    website: 'https://claude.ai',
    cookieHint: 'DevTools → Application → Cookies → sessionKey',
    cookieFields: ['sessionKey'],
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'gemini-web',
    name: 'Gemini Web (Advanced)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Free/Adv)',
    description: 'Gemini Advanced web platform with 2M context via Google session cookie.',
    website: 'https://gemini.google.com',
    cookieHint: 'Paste __Secure-1PSID; __Secure-1PSIDTS from gemini.google.com',
    cookieFields: ['__Secure-1PSID', '__Secure-1PSIDTS'],
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'deepseek-web',
    name: 'DeepSeek Web (Free)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Free)',
    description: 'Free unlimited DeepSeek-R1 reasoning via chat.deepseek.com web session.',
    website: 'https://chat.deepseek.com',
    cookieHint: 'DevTools → Application → LocalStorage / Cookies → userToken',
    cookieFields: ['userToken'],
    supportsTools: true,
  },
  {
    id: 'grok-web',
    name: 'Grok Web (X Premium)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (X Premium)',
    description: 'Grok 4 & Grok Code Fast via your X / Twitter Premium session cookies.',
    website: 'https://grok.com',
    cookieHint: 'Paste sso=...; sso-rw=... full cookie line from grok.com',
    cookieFields: ['sso', 'sso-rw'],
    supportsTools: true,
  },
  {
    id: 'perplexity-web',
    name: 'Perplexity Web (Pro)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Pro)',
    description: 'Unlimited Pro search and model switching (Claude 5 / Sonar / GPT-5).',
    website: 'https://www.perplexity.ai',
    cookieHint: 'DevTools → Application → Cookies → __Secure-next-auth.session-token',
    cookieFields: ['__Secure-next-auth.session-token'],
    supportsTools: true,
  },
  {
    id: 'poe-web',
    name: 'Poe Web (Quora)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session',
    description: 'Access hundreds of bots on Poe.com using your p-b cookie token.',
    website: 'https://poe.com',
    cookieHint: 'DevTools → Application → Cookies → p-b',
    cookieFields: ['p-b'],
    supportsTools: true,
  },
  {
    id: 'phind-web',
    name: 'Phind Web (Pro)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session',
    description: 'Phind 70B and developer search engine with session cookie.',
    website: 'https://www.phind.com',
    cookieHint: 'DevTools → Cookies → phindId or session token',
    supportsTools: true,
  },
  {
    id: 'blackbox-web',
    name: 'Blackbox AI Web',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session',
    description: 'Blackbox code intelligence and agentic coding via session token.',
    website: 'https://app.blackbox.ai',
    cookieHint: 'Paste __Secure-authjs.session-token from app.blackbox.ai',
    cookieFields: ['__Secure-authjs.session-token'],
    supportsTools: true,
  },
  {
    id: 'v0-web',
    name: 'Vercel v0 Web',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session',
    description: 'Vercel v0 generative UI design engine via Vercel session token.',
    website: 'https://v0.dev',
    cookieHint: 'DevTools → Cookies → _vercel_jwt or session cookie',
    supportsTools: true,
  },
  {
    id: 'bolt-web',
    name: 'Bolt.new Web',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session',
    description: 'Bolt.new fullstack WebContainer execution session.',
    website: 'https://bolt.new',
    cookieHint: 'Paste sb-*-auth-token session from bolt.new',
    supportsTools: true,
  },
  {
    id: 'lovable-web',
    name: 'Lovable.dev Web',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session',
    description: 'Lovable GPT-engineer fullstack web builder session.',
    website: 'https://lovable.dev',
    cookieHint: 'Paste session cookie from lovable.dev',
    supportsTools: true,
  },
  {
    id: 'cursor-web',
    name: 'Cursor IDE Web/Session',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Session Token',
    description: 'Cursor Pro account session token for fast premium composer access.',
    website: 'https://cursor.com',
    cookieHint: 'Paste WorkosCursorSessionToken from cursor.com',
    cookieFields: ['WorkosCursorSessionToken'],
    supportsTools: true,
  },
  {
    id: 'antigravity-web',
    name: 'Antigravity (Google)',
    category: 'web-cookie',
    categoryLabel: 'Sign-In Sessions',
    authTypes: ['oauth', 'cookie'],
    badge: 'Auto Sign-In',
    description: 'Routes Gemini through your existing local Google sign-in — detected automatically, no key or cookie paste needed. Advanced: paste a cookie only to override.',
    website: 'https://antigravity.google',
    cookieHint: 'Optional override — SUTRA auto-uses the local Google sign-in (~/.gemini/oauth_creds.json) when present',
    supportsTools: true,
  },
  {
    id: 'antigravity',
    name: 'Antigravity Session',
    category: 'web-cookie',
    categoryLabel: 'Sign-In Sessions',
    authTypes: ['oauth', 'cookie'],
    badge: 'Auto Sign-In',
    description: 'Zero-config Google Antigravity access via the local Google sign-in on this machine; optionally pair a Base URL to route through a self-hosted bridge runtime.',
    website: 'https://antigravity.google',
    cookieHint: 'Optional override — SUTRA auto-uses the local Google sign-in (~/.gemini/oauth_creds.json) when present',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'qoder-web',
    name: 'Qoder AI Web',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie', 'oauth'],
    badge: 'Session & OAuth',
    description: 'Qoder coding agent platform with session cookie authentication.',
    website: 'https://qoder.ai',
    cookieHint: 'Paste qoder_session_token from qoder.ai',
    supportsTools: true,
  },
  {
    id: 'glm-web',
    name: 'GLM Web Session',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'ChatGLM Session',
    description: 'chatglm.cn web session for GLM chat models.',
    website: 'https://chatglm.cn',
    cookieHint: 'Paste session cookies from chatglm.cn',
    cookieFields: ['chatglm_session'],
    supportsTools: false,
  },
  {
    id: 'qwen-web',
    name: 'Qwen Web (chat.qwen.ai)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Free)',
    description: 'Free Qwen3 chat models via your chat.qwen.ai web login session.',
    website: 'https://chat.qwen.ai',
    cookieHint: 'DevTools → Application → Cookies / Local Storage → token from chat.qwen.ai',
    cookieFields: ['token'],
    supportsTools: false,
  },
  {
    id: 'kimi-web',
    name: 'Kimi Web (kimi.com)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Free)',
    description: 'Moonshot Kimi K2 web assistant for long-context document chat.',
    website: 'https://www.kimi.com',
    cookieHint: 'DevTools → Application → Local Storage / Cookies → access_token or refresh_token from kimi.com',
    cookieFields: ['access_token', 'refresh_token'],
    supportsTools: false,
  },
  {
    id: 'meta-ai',
    name: 'Meta AI Web',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Free)',
    description: 'Meta AI Llama-powered chat at meta.ai using your Facebook web session.',
    website: 'https://www.meta.ai',
    cookieHint: 'Sign in at meta.ai, then DevTools → Application → Cookies → xs and datr',
    cookieFields: ['xs', 'datr'],
    supportsTools: false,
  },
  {
    id: 'duckduckgo-chat',
    name: 'DuckDuckGo Duck.ai',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Free)',
    description: 'Anonymous free chats with GPT-4o mini, Claude Haiku, Llama, and Mistral models on duck.ai.',
    website: 'https://duck.ai',
    cookieHint: 'Open duck.ai signed in, then DevTools → Application → Cookies → duckai_token',
    cookieFields: ['duckai_token'],
    supportsTools: false,
  },
  {
    id: 'copilot-web',
    name: 'Microsoft Copilot Web',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Microsoft)',
    description: 'Microsoft Copilot web chat via your signed-in Microsoft account session.',
    website: 'https://copilot.microsoft.com',
    cookieHint: 'Sign in at copilot.microsoft.com, then DevTools → Application → Cookies → _U',
    cookieFields: ['_U'],
    supportsTools: false,
  },
  {
    id: 'huggingchat-web',
    name: 'HuggingChat Web',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session (Free)',
    description: 'HuggingFace HuggingChat open-model web interface via your huggingface.co session.',
    website: 'https://huggingface.co/chat',
    cookieHint: 'Sign in at huggingface.co, then DevTools → Application → Cookies → token',
    cookieFields: ['token'],
    supportsTools: false,
  },
  {
    id: 'coze-web',
    name: 'Coze Web (ByteDance)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session',
    description: 'Coze bot platform web session for GPT-4o and Doubao powered bots.',
    website: 'https://www.coze.com',
    cookieHint: 'DevTools → Application → Cookies → sessionid from www.coze.com',
    cookieFields: ['sessionid'],
    supportsTools: false,
  },
  {
    id: 'mistral-web',
    name: 'Le Chat (Mistral Web)',
    category: 'web-cookie',
    categoryLabel: 'Web Session Cookies',
    authTypes: ['cookie'],
    badge: 'Cookie Session',
    description: 'Mistral Le Chat web session (Mistral Large and Codestral) from chat.mistral.ai.',
    website: 'https://chat.mistral.ai',
    cookieHint: 'DevTools → Application → Cookies → session from chat.mistral.ai',
    cookieFields: ['session'],
    supportsTools: false,
  },

  // 3. INFERENCE HOSTS & GPU CLOUDS (21)
  {
    id: 'together',
    name: 'Together AI',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'DeepSeek V3 / Llama 4 / FLUX',
    description: 'High performance open-source model inference and fine-tuning platform.',
    website: 'https://together.ai',
    docUrl: 'https://api.together.xyz/settings/api-keys',
    placeholder: 'tog_...',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'Fast Inference & Function Calling',
    description: 'Ultra-fast compound AI models and vision with structured JSON outputs.',
    website: 'https://fireworks.ai',
    docUrl: 'https://fireworks.ai/api-keys',
    placeholder: 'fw_...',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'cerebras',
    name: 'Cerebras Cloud',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: '1800+ tok/s Wafer-Scale Engine',
    description: 'World fastest inference engine on Wafer Scale Engine CS-3 hardware.',
    website: 'https://cerebras.ai',
    docUrl: 'https://cloud.cerebras.ai',
    placeholder: 'csk-...',
    supportsTools: true,
  },
  {
    id: 'sambanova',
    name: 'SambaNova Cloud',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'SN40L Reconfigurable Dataflow',
    description: 'Ultra-fast full-precision 16-bit Llama 3.3 70B and DeepSeek R1.',
    website: 'https://sambanova.ai',
    docUrl: 'https://cloud.sambanova.ai/apis',
    placeholder: 'samba_...',
    supportsTools: true,
  },
  {
    id: 'hyperbolic',
    name: 'Hyperbolic AI',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'Decentralized GPU Compute',
    description: 'Low-cost decentralized H100 inference for DeepSeek R1 and Llama 3.3.',
    website: 'https://hyperbolic.xyz',
    docUrl: 'https://app.hyperbolic.xyz/settings',
    placeholder: 'hyp_...',
    supportsTools: true,
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'Serverless GPUs',
    description: 'Pay-per-token serverless LLM, embeddings, and FLUX image inference.',
    website: 'https://deepinfra.com',
    docUrl: 'https://deepinfra.com/dash/api_keys',
    placeholder: 'di_...',
    supportsTools: true,
  },
  {
    id: 'novita',
    name: 'Novita AI',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'LLMs & Image Generation',
    description: 'Elastic serverless LLMs, FLUX.1, and LoRA fine-tuned model hosting.',
    website: 'https://novita.ai',
    docUrl: 'https://novita.ai/settings/key-management',
    placeholder: 'nov_...',
    supportsTools: true,
  },
  {
    id: 'lepton',
    name: 'Lepton AI',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'Photon Cloud',
    description: 'Sub-second AI services and custom model deployments.',
    website: 'https://lepton.ai',
    docUrl: 'https://dashboard.lepton.ai',
    placeholder: 'lep_...',
    supportsTools: true,
  },
  {
    id: 'replicate',
    name: 'Replicate',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'FLUX.1 / Whisper / Video',
    description: 'Run thousands of open-source models in the cloud with one line of code.',
    website: 'https://replicate.com',
    docUrl: 'https://replicate.com/account/api-tokens',
    placeholder: 'r8_...',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'nebius',
    name: 'Nebius AI Studio',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'Enterprise AI Cloud',
    description: 'European AI cloud with high-throughput H100/H200 cluster inference.',
    website: 'https://nebius.ai',
    docUrl: 'https://studio.nebius.ai',
    placeholder: 'neb_...',
    supportsTools: true,
  },
  {
    id: 'scaleway',
    name: 'Scaleway Generative APIs',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'EU Sovereign Cloud',
    description: 'GDPR-compliant European serverless inference with instant endpoints.',
    website: 'https://scaleway.com',
    docUrl: 'https://console.scaleway.com',
    placeholder: 'scw_...',
    supportsTools: true,
  },
  {
    id: 'ovhcloud',
    name: 'OVHcloud AI Endpoints',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'EU Private Infrastructure',
    description: 'Private, secure model endpoints hosted in European data centers.',
    website: 'https://ovhcloud.com',
    docUrl: 'https://endpoints.ai.cloud.ovh.net',
    placeholder: 'ovh_...',
    supportsTools: true,
  },
  {
    id: 'baseten',
    name: 'Baseten',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'Truss / High Throughput',
    description: 'Model deployment platform powered by Truss and ultra-fast cold starts.',
    website: 'https://baseten.co',
    docUrl: 'https://app.baseten.co/settings/api_keys',
    placeholder: 'base_...',
    supportsTools: true,
  },
  {
    id: 'featherless',
    name: 'Featherless AI',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: '10,000+ HuggingFace Models',
    description: 'Instant access to over 10,000 HuggingFace open-weight models on-demand.',
    website: 'https://featherless.ai',
    docUrl: 'https://featherless.ai',
    placeholder: 'feat_...',
    supportsTools: true,
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow (SiliconCloud)',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'DeepSeek / Qwen / GLM',
    description: 'Cost-effective high-concurrency inference engine in Asia Pacific.',
    website: 'https://siliconflow.cn',
    docUrl: 'https://cloud.siliconflow.cn/account/ak',
    placeholder: 'sk-...',
    supportsTools: true,
  },
  {
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'Llama 3.3 / Nemotron / DeepSeek R1 (free NIM tier)',
    description: 'NVIDIA-hosted OpenAI-compatible inference for Llama 3.3, Nemotron, DeepSeek R1, Qwen Coder, and Mixtral with a free build.nvidia.com key.',
    website: 'https://build.nvidia.com',
    docUrl: 'https://build.nvidia.com/docs/api-catalog',
    placeholder: 'nvapi-...',
    defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
    supportsTools: true,
    supportsVision: false,
  },
  {
    id: 'lambda',
    name: 'Lambda Cloud Inference',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'GPU Cloud On-Demand Inference',
    description: 'Lambda GPU cloud serving Llama and DeepSeek models through an OpenAI-compatible API.',
    website: 'https://lambda.ai',
    docUrl: 'https://docs.lambda.ai',
    placeholder: 'ln_...',
    defaultBaseUrl: 'https://api.lambda.ai/v1',
    supportsTools: false,
  },
  {
    id: 'friendliai',
    name: 'FriendliAI',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'Serverless & Dedicated Endpoints',
    description: 'FriendliEngine high-throughput serving of Llama, DeepSeek, and Qwen models.',
    website: 'https://friendli.ai',
    docUrl: 'https://suite.friendli.ai',
    placeholder: 'fli_...',
    defaultBaseUrl: 'https://inference.friendli.ai/v1',
    supportsTools: true,
  },
  {
    id: 'kluster',
    name: 'Kluster.ai',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'Affordable Live & Batch Inference',
    description: 'Cost-effective OpenAI-compatible hosting for DeepSeek, Qwen, and Llama models.',
    website: 'https://kluster.ai',
    docUrl: 'https://platform.kluster.ai',
    placeholder: 'klu_...',
    defaultBaseUrl: 'https://api.kluster.ai/v1',
    supportsTools: true,
  },
  {
    id: 'nscale',
    name: 'Nscale',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'EU Sovereign GPU Cloud',
    description: 'European GPU cloud with serverless OpenAI-compatible inference for open-weight models.',
    website: 'https://nscale.com',
    docUrl: 'https://console.nscale.com',
    placeholder: 'nsk_...',
    defaultBaseUrl: 'https://api.nscale.com/v1',
    supportsTools: true,
  },
  {
    id: 'gmi-cloud',
    name: 'GMI Cloud',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key'],
    badge: 'H200 HGX Clusters',
    description: 'High-performance GPU cloud serving open-weight models via OpenAI-compatible endpoints.',
    website: 'https://gmicloud.ai',
    docUrl: 'https://console.gmicloud.ai',
    placeholder: 'gmi_...',
    defaultBaseUrl: 'https://api.gmi-serving.com/v1',
    supportsTools: true,
  },

  // 4. REGIONAL & ASIA-PACIFIC LEADERS (15)
  {
    id: 'qwen',
    name: 'Alibaba Qwen (Tongyi Qianwen)',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'Qwen3 Coder Plus / Qwen3-Max',
    description: 'Top-tier code generation and multilingual mathematical reasoning.',
    website: 'https://bailian.console.aliyun.com',
    docUrl: 'https://bailian.console.aliyun.com',
    placeholder: 'sk-...',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI (GLM-4)',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'GLM-4.6 / GLM Coding Plans',
    description: 'Zhipu GLM flagship models served from both https://open.bigmodel.cn and https://z.ai international endpoints.',
    website: 'https://bigmodel.cn',
    docUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    placeholder: 'zhipu_...',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'glm',
    name: 'GLM Coding Plan (Z.ai)',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'GLM-4.6 Coding Plans',
    description: 'Zhipu GLM coding-plan API, works with both https://api.z.ai/api/paas/v4 and https://open.bigmodel.cn/api/paas/v4.',
    website: 'https://z.ai',
    docUrl: 'https://z.ai/manage-apikey/apikey-list',
    placeholder: 'KeyId.Secret...',
    defaultBaseUrl: 'https://api.z.ai/api/paas/v4',
    supportsTools: true,
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI (Kimi)',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key', 'cookie'],
    badge: 'Kimi K2 Long Context',
    description: 'Kimi K2 long-context document comprehension with agentic tool use and web retrieval.',
    website: 'https://moonshot.cn',
    docUrl: 'https://platform.moonshot.cn/console/api-keys',
    placeholder: 'sk-...',
    supportsTools: true,
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'MiniMax M1 / Video / Voice',
    description: 'Long-context MoE reasoning with expressive speech synthesis and video generation.',
    website: 'https://minimaxi.com',
    docUrl: 'https://platform.minimaxi.com',
    placeholder: 'mini_...',
    supportsTools: true,
  },
  {
    id: 'baichuan',
    name: 'Baichuan AI',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'Baichuan 4 / Omni',
    description: 'High-performing medical and domain-specific knowledge models.',
    website: 'https://baichuan-ai.com',
    docUrl: 'https://platform.baichuan-ai.com',
    placeholder: 'sk-...',
    supportsTools: true,
  },
  {
    id: 'yi-01ai',
    name: '01.AI (Yi Series)',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'Yi-Lightning / Yi-Large',
    description: 'High-speed bilingual reasoning developed by Dr. Kai-Fu Lee.',
    website: 'https://01.ai',
    docUrl: 'https://platform.01.ai',
    placeholder: 'yi_...',
    supportsTools: true,
  },
  {
    id: 'doubao',
    name: 'ByteDance Doubao (Volcengine)',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'Doubao Pro / Vision',
    description: 'ByteDance scalable foundation models powering enterprise TikTok/Lark apps.',
    website: 'https://volcengine.com',
    docUrl: 'https://console.volcengine.com/ark',
    placeholder: 'volc_...',
    supportsTools: true,
  },
  {
    id: 'hunyuan',
    name: 'Tencent Hunyuan',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'Hunyuan Large / 3D',
    description: 'Tencent 389B MoE architecture with deep Chinese NLP & 3D synthesis.',
    website: 'https://hunyuan.tencent.com',
    docUrl: 'https://console.cloud.tencent.com',
    placeholder: 'tenc_...',
    supportsTools: true,
  },
  {
    id: 'sarvam',
    name: 'Sarvam AI',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'Indic Languages 10+',
    description: 'Frontier foundation models and speech synthesis for Indian languages.',
    website: 'https://sarvam.ai',
    docUrl: 'https://dashboard.sarvam.ai',
    placeholder: 'sarv_...',
    defaultBaseUrl: 'https://api.sarvam.ai/v1',
    models: ['sarvam-105b', 'sarvam-m', 'sarvam-2b'],
    supportsTools: true,
  },
  {
    id: 'upstage',
    name: 'Upstage Solar',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'Solar Pro 22B / Document AI',
    description: 'South Korean leader in compact high-efficiency LLMs and OCR Document AI.',
    website: 'https://upstage.ai',
    docUrl: 'https://console.upstage.ai',
    placeholder: 'up_...',
    supportsTools: true,
  },
  {
    id: 'stepfun',
    name: 'StepFun (Step AI)',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'Step-2 / Step-1V Multimodal',
    description: 'Shanghai-based Step-2 flagship and Step-1V multimodal model family.',
    website: 'https://platform.stepfun.com',
    docUrl: 'https://platform.stepfun.com/interface-key',
    placeholder: 'sk-...',
    defaultBaseUrl: 'https://api.stepfun.com/v1',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'bytedance-volcengine',
    name: 'ByteDance Ark (International)',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'Ark Intl OpenAI-Compatible',
    description: 'BytePlus / Volcengine Ark international endpoint serving Doubao and Seed models outside China.',
    website: 'https://www.byteplus.com',
    docUrl: 'https://console.byteplus.com/ark',
    placeholder: 'ark_...',
    defaultBaseUrl: 'https://ark.ap-southeast.bytepluses.com/api/v3',
    supportsTools: true,
  },
  {
    id: 'dashscope',
    name: 'Alibaba Model Studio (DashScope)',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'Compatible Mode Endpoint',
    description: 'Alibaba Cloud DashScope OpenAI-compatible mode for Qwen, Wanx, and embeddings.',
    website: 'https://www.alibabacloud.com',
    docUrl: 'https://bailian.console.alibabacloud.com',
    placeholder: 'sk-...',
    defaultBaseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'baidu-qianfan',
    name: 'Baidu Qianfan Platform',
    category: 'regional',
    categoryLabel: 'Regional & Asia-Pacific',
    authTypes: ['api-key'],
    badge: 'ERNIE Enterprise Models',
    description: 'Baidu AI Cloud Qianfan serving ERNIE and DeepSeek via an OpenAI-compatible v2 API.',
    website: 'https://cloud.baidu.com',
    docUrl: 'https://console.bce.baidu.com/iam',
    placeholder: 'bce_...',
    defaultBaseUrl: 'https://qianfan.baidubce.com/v2',
    supportsTools: true,
  },

  // 5. ENTERPRISE CLOUD & GATEWAYS (11)
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'gateways',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key'],
    badge: '200+ Unified Models',
    description: 'Unified aggregator routing to 200+ frontier and open-weight models.',
    website: 'https://openrouter.ai',
    docUrl: 'https://openrouter.ai/keys',
    placeholder: 'sk-or-...',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI Service',
    category: 'enterprise-cloud',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key'],
    badge: 'Microsoft Cloud Compliance',
    description: 'Enterprise Azure hosting for GPT-5 with SOC2, HIPAA, and ISO certifications.',
    website: 'https://azure.microsoft.com',
    docUrl: 'https://portal.azure.com',
    placeholder: 'azure_key_...',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    category: 'enterprise-cloud',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key'],
    badge: 'Claude / Nova / Llama on AWS',
    description: 'Serverless access to Claude 5, Amazon Nova, and Llama 4 on AWS.',
    website: 'https://aws.amazon.com/bedrock',
    placeholder: 'AWS_ACCESS_KEY_ID',
    supportsTools: true,
  },
  {
    id: 'google-vertex',
    name: 'Google Cloud Vertex AI',
    category: 'enterprise-cloud',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key', 'oauth'],
    badge: 'GCP Enterprise Gemini',
    description: 'Google Cloud enterprise generative AI platform with custom tuning.',
    website: 'https://cloud.google.com/vertex-ai',
    placeholder: 'GCP_SERVICE_ACCOUNT_JSON',
    supportsTools: true,
  },
  {
    id: 'cloudflare-workers-ai',
    name: 'Cloudflare Workers AI',
    category: 'enterprise-cloud',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key'],
    badge: 'Sub-10ms Edge GPU',
    description: 'Global edge network GPU inference with zero cold starts.',
    website: 'https://ai.cloudflare.com',
    docUrl: 'https://dash.cloudflare.com',
    placeholder: 'cf_ai_...',
    supportsTools: true,
  },
  {
    id: 'portkey',
    name: 'Portkey AI Gateway',
    category: 'gateways',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key'],
    badge: 'AI Gateway & Cache',
    description: 'Unified AI gateway with load balancing, caching, and guardrails.',
    website: 'https://portkey.ai',
    docUrl: 'https://app.portkey.ai',
    placeholder: 'pk_...',
    supportsTools: true,
  },
  {
    id: 'helicone',
    name: 'Helicone AI Observability',
    category: 'gateways',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key'],
    badge: 'Tracing & Cost Management',
    description: 'LLM observability, caching, rate limiting, and prompt experiments.',
    website: 'https://helicone.ai',
    docUrl: 'https://helicone.ai/dashboard',
    placeholder: 'sk-heli-...',
    supportsTools: true,
  },
  {
    id: 'litellm',
    name: 'LiteLLM Proxy',
    category: 'gateways',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key'],
    badge: 'OpenAI Format Universal Proxy',
    description: 'Call 100+ LLMs using the OpenAI input/output format.',
    website: 'https://litellm.ai',
    placeholder: 'sk-...',
    supportsTools: true,
  },
  {
    id: 'writer',
    name: 'Writer (Palmyra)',
    category: 'enterprise-cloud',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key'],
    badge: 'Palmyra Enterprise LLMs',
    description: 'Enterprise Palmyra models with function calling, graph-based RAG, and compliance tooling.',
    website: 'https://writer.com',
    docUrl: 'https://dev.writer.com',
    placeholder: 'wr_...',
    defaultBaseUrl: 'https://api.writer.com/v1',
    supportsTools: true,
  },
  {
    id: 'vercel-ai-gateway',
    name: 'Vercel AI Gateway',
    category: 'gateways',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key'],
    badge: 'One Key, Many Models',
    description: 'Route to frontier and open-weight models through Vercel with automatic fallbacks.',
    website: 'https://vercel.com/ai-gateway',
    docUrl: 'https://vercel.com/docs/ai-gateway',
    placeholder: 'vck_...',
    defaultBaseUrl: 'https://ai-gateway.vercel.sh/v1',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'requesty',
    name: 'Requesty Router',
    category: 'gateways',
    categoryLabel: 'Enterprise Gateways & Routers',
    authTypes: ['api-key'],
    badge: 'Unified Router & Guardrails',
    description: 'Single OpenAI-compatible gateway across many model providers with caching and spend controls.',
    website: 'https://requesty.ai',
    docUrl: 'https://app.requesty.ai/manage-api',
    placeholder: 'sk-...',
    defaultBaseUrl: 'https://router.requesty.ai/v1',
    supportsTools: true,
  },

  // 6. GENERATIVE MEDIA & VOICE (18)
  {
    id: 'runway',
    name: 'RunwayML (Gen-3 Alpha)',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Cinematic Video Generation',
    description: 'Photorealistic AI video synthesis and camera motion control.',
    website: 'https://runwayml.com',
    docUrl: 'https://app.runwayml.com/account/keys',
    placeholder: 'key_...',
  },
  {
    id: 'luma',
    name: 'Luma Dream Machine',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Physics-Accurate Video',
    description: 'High-speed, realistic video synthesis with consistent motion.',
    website: 'https://lumalabs.ai',
    docUrl: 'https://lumalabs.ai/dream-machine/api',
    placeholder: 'luma-...',
  },
  {
    id: 'kling',
    name: 'Kling AI (Kuaishou)',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'High Dynamic Video',
    description: 'State-of-the-art cinematic 1080p video generation.',
    website: 'https://klingai.com',
    placeholder: 'kling-...',
  },
  {
    id: 'pika',
    name: 'Pika Labs (Pika 2.0)',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key', 'cookie'],
    badge: 'Video & Effects',
    description: 'Dynamic video generation with sound effects and camera control.',
    website: 'https://pika.art',
    placeholder: 'pika_...',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs Voice AI',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Expressive Speech & SFX',
    description: 'Industry-standard voice cloning, TTS, and tactile sound design.',
    website: 'https://elevenlabs.io',
    docUrl: 'https://elevenlabs.io/app/api-keys',
    placeholder: 'xi_...',
  },
  {
    id: 'cartesia',
    name: 'Cartesia Sonic',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Ultra-Low Latency TTS (90ms)',
    description: 'State space architecture real-time conversational voice synthesis.',
    website: 'https://cartesia.ai',
    docUrl: 'https://play.cartesia.ai/keys',
    placeholder: 'car_...',
  },
  {
    id: 'playht',
    name: 'PlayHT 2.0',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Real-time Conversational Voice',
    description: 'Human-like conversational AI voice with emotion control.',
    website: 'https://play.ht',
    docUrl: 'https://play.ht/app/api-access',
    placeholder: 'play_...',
  },
  {
    id: 'deepgram',
    name: 'Deepgram Nova-2',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Speech-to-Text Transcription',
    description: 'Lightning-fast audio transcription and voice agent framework.',
    website: 'https://deepgram.com',
    docUrl: 'https://console.deepgram.com',
    placeholder: 'dg_...',
  },
  {
    id: 'stability-ai',
    name: 'Stability AI (SD3.5 / FLUX)',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Stable Diffusion 3.5 Large',
    description: 'Open photorealistic image generation, inpainting, and 3D meshes.',
    website: 'https://stability.ai',
    docUrl: 'https://platform.stability.ai/account/keys',
    placeholder: 'sk-...',
  },
  {
    id: 'midjourney-api',
    name: 'Midjourney API Relay',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key', 'cookie'],
    badge: 'V6.1 Photorealism',
    description: 'Artistic prompt execution via Discord/Web session bridge.',
    website: 'https://midjourney.com',
    placeholder: 'mj_...',
  },
  {
    id: 'suno-ai',
    name: 'Suno AI (v3.5 / v4)',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['cookie', 'api-key'],
    badge: 'Full Song Music Generation',
    description: 'Generate full 2-minute songs with vocals, lyrics, and instruments.',
    website: 'https://suno.com',
    cookieHint: 'Paste __client cookie session from suno.com',
  },
  {
    id: 'udio-ai',
    name: 'Udio AI Music',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['cookie', 'api-key'],
    badge: 'High-Fidelity Stereo Music',
    description: 'Studio-grade music synthesis and audio mastering.',
    website: 'https://udio.com',
    cookieHint: 'Paste session cookie from udio.com',
  },
  {
    id: 'leonardo',
    name: 'Leonardo AI Image Suite',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Phoenix Image Generation',
    description: 'Leonardo production image generation, upscaling, and canvas editing APIs.',
    website: 'https://leonardo.ai',
    docUrl: 'https://app.leonardo.ai/api-access',
    placeholder: 'leo_...',
  },
  {
    id: 'fal',
    name: 'fal.ai Diffusion Hub',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Fast FLUX Image & Video',
    description: 'Hosted diffusion endpoints for fast FLUX image generation and video models.',
    website: 'https://fal.ai',
    docUrl: 'https://fal.ai/dashboard/keys',
    placeholder: 'fal_...',
  },
  {
    id: 'ideogram',
    name: 'Ideogram API',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Typography & Text-in-Image',
    description: 'Best-in-class rendering of legible text inside generated images.',
    website: 'https://ideogram.ai',
    docUrl: 'https://ideogram.ai/api',
    placeholder: 'ideo_...',
  },
  {
    id: 'black-forest-labs',
    name: 'Black Forest Labs (FLUX)',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Official FLUX API',
    description: 'Official FLUX Kontext and FLUX text-to-image generation API from the makers of Stable Diffusion.',
    website: 'https://bfl.ai',
    docUrl: 'https://docs.bfl.ai',
    placeholder: 'bfl_...',
  },
  {
    id: 'recraft',
    name: 'Recraft AI',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Vector & Brand Images',
    description: 'SVG vector art, brand-consistent styles, and photorealistic image generation.',
    website: 'https://recraft.ai',
    docUrl: 'https://docs.recraft.ai',
    placeholder: 'rc_...',
  },
  {
    id: 'assemblyai',
    name: 'AssemblyAI Speech AI',
    category: 'media-audio',
    categoryLabel: 'Generative Media & Voice',
    authTypes: ['api-key'],
    badge: 'Speech-to-Text & Intelligence',
    description: 'Accurate transcription, speaker diarization, and audio intelligence APIs.',
    website: 'https://www.assemblyai.com',
    docUrl: 'https://www.assemblyai.com/dashboard/api-keys',
    placeholder: 'aai_...',
  },

  // 7. LOCAL & OFFLINE RUNTIMES (7)
  {
    id: 'ollama',
    name: 'Local Ollama Runtime',
    category: 'local-free',
    categoryLabel: 'Local Offline & Free Runtimes',
    authTypes: ['local', 'none'],
    badge: '100% Offline & Free',
    description: 'Ollama local server running on localhost:11434 with zero GPU fees.',
    website: 'https://ollama.com',
    defaultBaseUrl: 'http://localhost:11434',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'lmstudio',
    name: 'LM Studio Local Server',
    category: 'local-free',
    categoryLabel: 'Local Offline & Free Runtimes',
    authTypes: ['local', 'none'],
    badge: 'OpenAI API on localhost:1234',
    description: 'GUI local model loader with GPU offloading and OpenAI compatible /v1 endpoint.',
    website: 'https://lmstudio.ai',
    defaultBaseUrl: 'http://localhost:1234/v1',
    supportsTools: true,
  },
  {
    id: 'vllm',
    name: 'vLLM Inference Engine',
    category: 'local-free',
    categoryLabel: 'Local Offline & Free Runtimes',
    authTypes: ['local', 'api-key'],
    badge: 'PagedAttention High Throughput',
    description: 'High-throughput and memory-efficient LLM serving engine on localhost:8000.',
    website: 'https://vllm.ai',
    defaultBaseUrl: 'http://localhost:8000/v1',
    supportsTools: true,
  },
  {
    id: 'localai',
    name: 'LocalAI',
    category: 'local-free',
    categoryLabel: 'Local Offline & Free Runtimes',
    authTypes: ['local', 'none'],
    badge: 'Self-Hosted OpenAI Drop-in',
    description: 'Self-hosted OpenAI replacement for audio, text, and image generation.',
    website: 'https://localai.io',
    defaultBaseUrl: 'http://localhost:8080/v1',
    supportsTools: true,
  },
  {
    id: 'jan-ai',
    name: 'Jan.ai Offline Engine',
    category: 'local-free',
    categoryLabel: 'Local Offline & Free Runtimes',
    authTypes: ['local', 'none'],
    badge: '100% Offline Local',
    description: 'Privacy-focused offline desktop assistant on localhost:1337.',
    website: 'https://jan.ai',
    defaultBaseUrl: 'http://localhost:1337/v1',
    supportsTools: true,
  },
  {
    id: 'pollinations',
    name: 'Pollinations AI',
    category: 'local-free',
    categoryLabel: 'Local Offline & Free Runtimes',
    authTypes: ['none'],
    badge: 'Free — no key needed',
    description: 'Free public generative AI for text, images, and video synthesis with no keys.',
    website: 'https://pollinations.ai',
    supportsTools: false,
    supportsVision: false,
  },
  {
    id: 'antigravity-ide',
    name: 'Antigravity IDE Bridge',
    category: 'local-free',
    categoryLabel: 'Local Offline & Free Runtimes',
    authTypes: ['local', 'cookie'],
    badge: 'Local IDE Runtime',
    description: 'Routes requests through a locally running Antigravity IDE runtime via an OpenAI-compatible bridge URL (set Base URL, e.g. http://localhost:PORT/v1). Falls back to the Google chain when unavailable.',
    website: 'https://antigravity.google',
    defaultBaseUrl: '',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'kilo',
    name: 'Kilo AI Gateway',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key', 'none'],
    badge: 'Keyless & Free Tier',
    description: 'Unified gateway providing keyless and free promotional model endpoints with high concurrency.',
    website: 'https://kilo.ai',
    docUrl: 'https://kilo.ai/docs',
    defaultBaseUrl: 'https://api.kilo.ai/api/gateway/v1',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'llm7',
    name: 'LLM7.io Gateway',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key', 'none'],
    badge: 'Free Tier Aggregator',
    description: 'Multi-model API gateway with 100 req/hr free tier across open-source models.',
    website: 'https://llm7.io',
    defaultBaseUrl: 'https://api.llm7.io/v1',
    supportsTools: true,
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Inference Providers',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Meta-Router Free Tier',
    description: 'Hugging Face router meta-endpoints with monthly free inference quota.',
    website: 'https://huggingface.co',
    docUrl: 'https://huggingface.co/docs/api-inference',
    defaultBaseUrl: 'https://router.huggingface.co/v1',
    supportsTools: true,
  },
  {
    id: 'opencode',
    name: 'OpenCode Zen Gateway',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'OpenCode Models',
    description: 'OpenAI-compatible gateway hosting specialized coding and reasoning open-weights models.',
    website: 'https://opencode.ai',
    defaultBaseUrl: 'https://api.opencode.ai/v1',
    supportsTools: true,
  },
  {
    id: 'ovh',
    name: 'OVHcloud AI Endpoints',
    category: 'inference-hosts',
    categoryLabel: 'Inference Hosts & GPU Clouds',
    authTypes: ['api-key', 'none'],
    badge: 'European AI Cloud',
    description: 'European sovereign AI endpoints with anonymous and authenticated free tiers.',
    website: 'https://www.ovhcloud.com/en/public-cloud/ai-endpoints',
    defaultBaseUrl: 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1',
    supportsTools: true,
  },
  {
    id: 'agnes',
    name: 'Agnes AI (Sapiens)',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Proprietary Agnes Models',
    description: 'LiteLLM and vLLM powered gateway serving Agnes reasoning and coding models.',
    website: 'https://platform.agnes-ai.com',
    defaultBaseUrl: 'https://api.agnes-ai.com/v1',
    supportsTools: true,
  },
  {
    id: 'reka',
    name: 'Reka AI',
    category: 'frontier',
    categoryLabel: 'Frontier Labs',
    authTypes: ['api-key'],
    badge: 'Native Multimodal & Vision',
    description: 'Native multimodal models with image, video, and audio understanding capabilities.',
    website: 'https://reka.ai',
    docUrl: 'https://docs.reka.ai',
    defaultBaseUrl: 'https://api.reka.ai/v1',
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: 'routeway',
    name: 'Routeway AI Router',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Zero-Cost Free Tier',
    description: 'Smart aggregator offering zero-cost free route pools across open models.',
    website: 'https://routeway.ai',
    defaultBaseUrl: 'https://api.routeway.ai/v1',
    supportsTools: true,
  },
  {
    id: 'bazaarlink',
    name: 'BazaarLink Gateway',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Auto Free Route',
    description: 'Decentralized AI gateway offering auto zero-cost model routing.',
    website: 'https://bazaarlink.ai',
    defaultBaseUrl: 'https://api.bazaarlink.ai/v1',
    supportsTools: true,
  },
  {
    id: 'ainative',
    name: 'AINative Studio',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Monthly Free Allowance',
    description: 'Unified studio router with monthly recurring token allowances on open weights.',
    website: 'https://ainative.studio',
    defaultBaseUrl: 'https://api.ainative.studio/v1',
    supportsTools: true,
  },
  {
    id: 'aion',
    name: 'Aion Labs Router',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Unified API Router',
    description: 'High-availability router connecting multiple global inference providers.',
    website: 'https://aionlabs.ai',
    defaultBaseUrl: 'https://api.aionlabs.ai/v1',
    supportsTools: true,
  },
  {
    id: 'requesty',
    name: 'Requesty AI Router',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Failover Routing Gateway',
    description: 'Smart failover and load balancing router with free model allocations.',
    website: 'https://requesty.ai',
    defaultBaseUrl: 'https://router.requesty.ai/v1',
    supportsTools: true,
  },
  {
    id: 'navy',
    name: 'NavyAI Unified Gateway',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Daily Free Tokens',
    description: 'Unified AI router providing 150K tokens/day free on open models.',
    website: 'https://navy.ai',
    defaultBaseUrl: 'https://api.navy.ai/v1',
    supportsTools: true,
  },
  {
    id: 'nara',
    name: 'NaraRouter AI',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Aggregator Gateway',
    description: 'High-throughput OpenAI-compatible router with recurring daily credits.',
    website: 'https://router.bynara.id',
    defaultBaseUrl: 'https://router.bynara.id/v1',
    supportsTools: true,
  },
  {
    id: 'sealion',
    name: 'SEA-LION (AI Singapore)',
    category: 'regional',
    categoryLabel: 'Regional & Multilingual Engines',
    authTypes: ['api-key'],
    badge: 'Regional Open Weights',
    description: 'AI Singapore official Southeast Asian language and instruction-tuned models.',
    website: 'https://sea-lion.ai',
    defaultBaseUrl: 'https://api.sea-lion.ai/v1',
    supportsTools: true,
  },
  {
    id: 'orcarouter',
    name: 'OrcaRouter AI',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Smart Fallback Router',
    description: 'Resilient OpenAI-compatible aggregator with rate-limited free aliases.',
    website: 'https://orcarouter.ai',
    defaultBaseUrl: 'https://api.orcarouter.ai/v1',
    supportsTools: true,
  },
  {
    id: 'unorouter',
    name: 'UnoRouter API',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Free Model Aggregator',
    description: 'Aggregator router offering rate-limited free open model routes.',
    website: 'https://unorouter.com',
    defaultBaseUrl: 'https://api.unorouter.com/v1',
    supportsTools: true,
  },
  {
    id: 'xkiro',
    name: 'xKiro Gateway',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Daily Free Tokens',
    description: 'High-speed gateway offering 5M tokens/day on its free model catalog.',
    website: 'https://xkiro.com',
    defaultBaseUrl: 'https://api.xkiro.com/v1',
    supportsTools: true,
  },
  {
    id: 'modelscope',
    name: 'ModelScope Community (Alibaba)',
    category: 'regional',
    categoryLabel: 'Regional & Multilingual Engines',
    authTypes: ['api-key'],
    badge: 'Qwen & DeepSeek Hub',
    description: 'Alibaba ModelScope community inference API with 2000 free requests/day across Qwen, DeepSeek, and GLM.',
    website: 'https://modelscope.cn',
    defaultBaseUrl: 'https://api-inference.modelscope.cn/v1',
    supportsTools: true,
  },
  {
    id: 'bai',
    name: 'B.AI Gateway',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Zero-Cost Gateway',
    description: 'OpenAI-compatible gateway with zero-cost free model access.',
    website: 'https://b.ai',
    defaultBaseUrl: 'https://api.b.ai/v1',
    supportsTools: true,
  },
  {
    id: 'anyapi',
    name: 'AnyAPI Gateway',
    category: 'gateways',
    categoryLabel: 'Gateways & Unified Aggregators',
    authTypes: ['api-key'],
    badge: 'Free Tier Aggregator',
    description: 'OpenAI-compatible router offering 100K free tokens/day on open models.',
    website: 'https://anyapi.ai',
    defaultBaseUrl: 'https://api.anyapi.ai/v1',
    supportsTools: true,
  },
];
